development: &default
  adapter: postgresql	
  encoding: unicode	
  host: localhost
  port: 5432
  database: nsd_100
  pool: 5
  username: nsd_100_admin
  password: -<3Y%Y"_xfr?nai	
  reconnect: true

staging: 		
  <<: *default		

test:		
  <<: *default  

production:		
  adapter: postgresql 
  encoding: unicode 
  host: ndx-100.c3n3fi9grsp4.us-west-2.rds.amazonaws.com
  port: 5432
  database: ndx100
  pool: 5
  username: ndx_100_admin
  password: <%= ENV["NDX_DB_PASSWORD"] %>
  reconnect: true		